### ISSUE TITLE
$scope.control.editor.config is null after publish

### ISSUE THREAD

**Issue by runegronkjaer** [leekelleher/umbraco-doc-type-grid-editor#39] opened 2016-01-27 10:36 UTC
I'm using v0.2.0 and I'm experiencing problems with $scope.control.editor.config that is null.
It's all in doctypegrideditor.controllers.js.

I will get an error on line 39 when clicking the item in the grid and it start to open the right dialog. It will say that you cannot use allowedDocTypes on undefined.
A check for null seems to fix the problem. But I guess the config should'nt be undefined in the first place?!

After fixing allowedDocTypes, the same thing will happen with enablePreview on line 57

/Rune

**Comment by leekelleher** [comment] 2016-01-28 10:55
@runegronkjaer Thanks for the info!

For clarification, which version of Umbraco are you using? and which web-browser?

**Comment by runegronkjaer** [comment] 2016-01-28 11:00
Sorry:
Umbraco v7.3.1
Browser: chrome

**Comment by leekelleher** [comment] 2016-04-01 12:53
@runegronkjaer (Sorry for not getting back to you sooner - again)

I've been trying to reproduce this issue today, but unfortunately I can't.  I am testing against Umbraco 7.4.2, so not sure if something has changed in Umbraco since v7.3.1?

Are you still able to reproduce this issue?
If so, would you be able to post the DTGE parts of your "grid.editors.config.js" config, please?

Thanks, Lee.

**Comment by mattbrailsford** [comment] 2016-09-16 20:37
Given this we've not received any further feedback and nobody else has reported this issue I'm going to close this issue. Feel free to reopen it if you find any further information.

**Closed by mattbrailsford** 2016-09-16 20:37 UTC
Labels: on hold
