### ISSUE TITLE
ImageCropper throws Not a valid Win32 FileTime

### ISSUE THREAD

**Issue by cheeseytoastie** [leekelleher/umbraco-doc-type-grid-editor#24] opened 2015-08-11 11:33 UTC
Loving the DocType Grid Editor! 

I've created a DocType with an ImageCropper on it - I'm trying to get the crop URL using 

Model.GetCropUrl("ProfilePicture", "Profile")

-		Model.GetCropUrl("ProfilePicture", "Profile")	'Model.GetCropUrl("ProfilePicture", "Profile")' threw an exception of type 'System.ArgumentOutOfRangeException'	string {System.ArgumentOutOfRangeException}
-		base	{"Not a valid Win32 FileTime."}	System.ArgumentException {System.ArgumentOutOfRangeException}

I'm sure I saw someone else saying about this as an issue but I can't find the post / issue now. Apologies if this has already been raised.

**Comment by mattbrailsford** [comment] 2015-08-11 11:41
Do you have a media picker value converter installed by any chance? Haven't
looked at the GetCropUrl code yet, but wondering if it tries to get the
media ID, but gets an IPublishedContent instead?

**Comment by cheeseytoastie** [comment] 2015-08-11 12:10
You mean like https://our.umbraco.org/projects/backoffice-extensions/multi-url-picker or https://our.umbraco.org/projects/website-utilities/gridmaps/ 

Yes then :)

**Comment by mattbrailsford** [comment] 2015-08-11 12:12
What property editor type is your ProfilePicture field?

**Comment by cheeseytoastie** [comment] 2015-08-11 12:14
A custom which is of type Umbraco.ImageCropper

**Comment by cheeseytoastie** [comment] 2015-08-11 12:23
I've just tried this on a scratch copy of Umbraco (latest release) without the other two packages installed and it does the same.

**Comment by mattbrailsford** [comment] 2015-08-11 12:28
Ahh, ok, I think I see where the issue is (though not sure how to fix it) but as part of GetCropUrl it uses the updatedate of the IPublishedContent to generate a cache key value. Unfortunately, the DTGE value doesn't have an update date, so it fails because the date is invalid. Ideally we should try and use the update date of the upper most node, however there isn't an easy way to get hold of this.

One way to stop this is to pass false into the cacheBuster option of GetCropUrl as this will stop it accessing the update date, though it will also stop the cache buster from working, however you could then just add a &rnd=XXX querystring onto the URL yourself, something like.

    Model.GetCropUrl("ProfilePicture", "Profile", cacheBuster = false) + "&rnd=" + DateTime.Now.Ticks

**Comment by mattbrailsford** [comment] 2015-08-11 12:35
Thing to note on that fix though is that DateTime.Now.Ticks would always change on every request. You could probably lookup a reference of the current umbraco page by using UmbracoContext.Current.PageId (I think that's what it's called) and then use the update date of that node.

This is all OTMH so subject to mistakes, but it should point you in the right direction.

**Comment by cheeseytoastie** [comment] 2015-08-11 12:37
Yup just tried:
profileImageUrl = Model.GetCropUrl(propertyAlias: "ProfilePicture", cropAlias: "profile", cacheBuster: false) + "&rnd=" + DateTime.Now.Ticks;
     
No exceptions now but an empty string is returned from GetCropUrl ....

**Comment by cheeseytoastie** [comment] 2015-08-11 12:40
Ahh.. it looks like the image isn't stored after uploading / picking. 

I'll change it to a block picker to fix my existing problem so it's not urgent but it's an interesting issue I hope?

**Comment by mattbrailsford** [comment] 2015-08-11 12:43
Yup, anything with an uploader won't work, so you should always use some kind of media picker.

Definitely an interesting issue though, which I think we may have found a proper fix for (the GetCropUrl issus at least, upload fields still won't work), but sounds like you make have a good enough workaround for the time being at least.

Matt

**Comment by mattbrailsford** [comment] 2015-08-11 18:37
Fixed in commit fdc4617eaf7b0670644c4dbdc2022d294b140adf

**Closed by mattbrailsford** 2015-08-11 18:37 UTC
