### ISSUE TITLE
Copying Nodes throws errors 

### ISSUE THREAD

**Issue by cheeseytoastie** [leekelleher/umbraco-doc-type-grid-editor#27] opened 2015-09-16 10:50 UTC
If you copy a content node that has some content via the doc type grid editor you get an ugly error for each piece of content in the grid when you hit that content in the back office.  I'm guessing it's where the child, hidden content nodes are created on the copy but not published so the preview call fails? 

<span ng-bind-html="notification.message" class="ng-binding">The URL returned a 404 (not found): <br><i>/2105</i><br> with data: <br><i>"id=5bf5ac58-371c-8572-9225-0e9c173dae3b&amp;docType=b3308c46-30d8-4d77-9b79-fa3696a9472f&amp;value=%7B%22name%22%3A%22test%22%2C%22heading%22%3A%22Test%22%2C%22bodyText%22%3A%22%3Cp%3ETo+break+the+copy+paste%3C%2Fp%3E%22%2C%22profilePicture%22%3A%22%22%7D&amp;viewPath=%2FViews%2FPartials%2F"</i><br>Contact your administrator for information.</span>

![image](https://cloud.githubusercontent.com/assets/3637223/9902805/2ccc7670-5c69-11e5-8263-1291b5d961e4.png)

**Comment by cheeseytoastie** [comment] 2015-09-16 10:56
I should note that publishing this content node and then manually clearing these errors makes it work again as normal. But for editors this looks a bit worrying.

**Comment by mattbrailsford** [comment] 2015-11-28 15:33
Duplicate of issue #18

**Closed by mattbrailsford** 2015-11-28 15:33 UTC
