### ISSUE TITLE
Tags' PropertyValueConverter isn't playing nicely

### ISSUE THREAD

**Issue by smdooley** [leekelleher/umbraco-doc-type-grid-editor#43] opened 2016-02-24 15:44 UTC
The Grid Layout JSON shows that the Umbraco Tags property has been populated but is returning null or empty when attempting to render on the front-end i.e Model.HasValue("filters") is null

`{
  "grid": 12,
  "allowAll": false,
  "allowed": [
	"button",
	"heading",
	"latestItems",
	"htmlBlock",
	"embedSnippet",
	"embedVideo",
	"imagePicker"
  ],
  "controls": [
	{
	  "value": {
		"docType": "6b2b05ba-a3be-4e5a-bdb5-98a8628d45e9",
		"value": {
		  "name": "Latest News",
		  "brandColour": "ffdc00",
		  "limit": "",
		  "filters": [
			"Scotland"
		  ],
		  "filter": "Scotland"
		},
		"id": "218a99f2-a73b-447d-40ea-7363bb9ce7fd"
	  },
	  "editor": {
		"alias": "latestItems"
	  }
	}
  ]
}`

Here is a link to the Umbraco Forum post [Umbraco.Tags value is always empty](https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/75320-umbracotags-value-is-always-empty)

**Comment by Kimtho** [comment] 2016-03-02 08:10
I am getting the following error:
```
System.Exception: Type validation failed. The value type: 'WhereSelectEnumerableIterator`2' does not match the DataType in PropertyType with alias: 'tags'
   at Umbraco.Core.Models.Property.set_Value(Object value)
   at Umbraco.Core.Models.Property..ctor(PropertyType propertyType, Object value)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValue(String id, String contentTypeAlias, String dataJson)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.<>c__DisplayClass1.<ConvertValueToContent>b__0()
   at Umbraco.Core.Cache.NullCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValueToContent(String id, String contentTypeAlias, String dataJson)
   at ASP._Page_app_plugins_doctypegrideditor_render_doctypegrideditor_cshtml.Execute() in \App_Plugins\DocTypeGridEditor\Render\DocTypeGridEditor.cshtml:line 26
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views___Default___Partials_grid_editors_base_cshtml.Execute() in \Partials\Grid\Editors\Base.cshtml:line 20
```

**Comment by leekelleher** [comment] 2016-04-01 13:09
@smdooley @Kimtho Apologies for not get back to you sooner on this issue.

Only a quick update to say that I can reproduce the issue (in Umbraco 7.4.2) and that it appears to be an issue (bug!) with Umbraco's Tags PropertyValueConverter.  Unfortunately it's not something that we can fix within DTGE.

I'll leave this issue open for now, as I'm going to dig into the Umbraco Core code to see if I can identify the cause of the issue.

**Comment by leekelleher** [comment] 2016-04-01 15:58
OK, I've spent a few hours digging deep into the Umbraco Core code, and found the cause.  It looks to be an Umbraco issue, not something we can fix within DTGE.

The underlying issue is that the Tags property-editor handles it's value conversion different to other property-editors. This goes beyond the remit of what DTGE can understand or handle.
(The same issue will hit Nested Content too)

I've raised an issue on the Umbraco tracker: http://issues.umbraco.org/issue/U4-8279

**Comment by mattbrailsford** [comment] 2016-09-16 20:35
Based upon discussions Lee and I have had with Shannon, we have got clarification on the value conversion issue and a suggested workaround for our code has been suggested. However, in digging into the Tags property editor, it is clear now that it has been designed and built in such a way that it is only meant to be used once per page, and really should be used directly on the page doc type itself so in that case is unsuitable for use in DTGE.

With that in mind I'm going to close this issue and simply state that the tags property editor is not compatible with DTGE

**Closed by mattbrailsford** 2016-09-16 20:35 UTC
Labels: cantfix, on hold, umbraco
